(ns daiklave.corebooks.charms)

(def archery-charms [{:description "With skill and effort, the Exalt guides her arrow to its mark. The Exalt may use this Charm to supplement a withering or decisive attack, reducing the benefits of cover. The defense bonus of heavy and light cover is reduced by one, while characters under no cover suffer a -1 penalty to their normal Defense.\n\nIn addition, after taking an aim action, the Solar may activate this Charm to strike an opponent in full cover. The Exalt shoots along an arc or angle that perfectly matches her opponent’s position. So long as there is some opening where an arrow can get through, Wise Arrow treats a character in full cover as if he merely has +3 Defense.", :category :charm, :prereq-charms "None", :ability :archery, :name "Wise Arrow", :type :supplemental, :duration "Instant", :page 255, :keywords "Uniform", :min-ability 2, :cost "1m", :min-essence 1}
                     {:description "The Exalt opens her eyes not to the visual world, but to the world of Essence, sensing her target in that fashion. She may make an Archery attack without penalties for visual conditions. Smoke, fog, and pitch darkness are no longer a problem for her, though other factors such as high winds and cover still apply against the attack. \n\nAt Archery 5+, Essence 3+, the Solar can momentarily see through cover, perceiving her targets as silhouettes the colors of bright anima.", :category :charm, :prereq-charms "Wise Arrow", :ability :archery, :name "Sight Without Eyes", :keywords "None", :type :supplemental, :duration "One tick", :page 255, :min-ability 3, :cost "1m", :min-essence 1}
                     {:description "Drawing upon the perfect moment to shoot, the Solar sees nothing but her target. Upon becoming the beneficiary of a distract gambit (p. 200), if the Solar’s new Initiative would allow her to act immediately, she may use this Charm to fire a ranged decisive attack from up to long range without an aim action. In addition, if the Lawgiver has under seven Initiative, the base damage of this attack gains (Essence) bonus dice.", :category :charm, :prereq-charms "Sight Without Eyes", :ability :archery, :name "Blood Without Balance", :keywords "Decisive-only", :type :supplemental, :duration "Instant", :page 256, :min-ability 4, :cost "3m", :min-essence 1}
                     {:description "The Solar nocks an arrow with purpose, sending a tremulous pulse through her surroundings as she gathers hurricane force into her bowstring. The Solar makes a withering attack from short or close range, and a pulverizing bolt of force surrounds her arrow as it leaps from her bow. If the attack does at least as much damage as her target’s Stamina, that Initiative is lost rather than transferred to the Solar, and the target is knocked down and back an entire range band. This force is sufficient to end a rush against any target.", :category :charm, :prereq-charms "Sight Without Eyes", :ability :archery, :name "Force Without Fire", :keywords "Withering-only", :type :supplemental, :duration "Instant", :page 256, :min-ability 4, :cost "3m", :min-essence 1}
                     {:description "The Solar strums her bow and fills the air with sharp notes. This Charm allows the Exalt to attack multiple targets, or a single target multiple times, by spreading her total current Initiative between decisive attacks. Each attack must contain at least three Initiative, and extra Initiative must be spread as evenly as possible between shots. For example, an Exalt with 11 Initiative attacking three targets could make two decisive attacks with four raw damage, and a third with only three. In addition, each 10 she rolls on an attack increases the base damage of that attack by one. The Exalt’s Initiative does not reset until she has completed every attack, and she may not make more attacks than she has ammunition or Dexterity. This attack can be made without an aim action.", :category :charm, :prereq-charms "Wise Arrow", :ability :archery, :name "Trance Of Unhesitating Speed", :keywords "Decisive-only", :type :supplemental, :duration "Instant", :page 256, :min-ability 3, :cost "3m, 1wp", :min-essence 1}
                     {:description "Palming a mote of Essence, the Lawgiver pulls a thorn from her heart and fires it at the breast of her enemy. With this Charm, the Solar may continue firing her bow even when she has run out of arrows. \n\nIn addition, once per scene, the Exalt may suffuse a phantom or physical arrow with the import of one of her Intimacies. Doing so gives her attack a number of nonCharm bonus dice equal to the Intimacy’s strength, but also temporarily numbs her to that Intimacy. She may not use this attack again until she has spent significant effort in restoring or remembering the Intimacy, or in the case of a negative Intimacy, has been reminded of her motivation for her ire.\n\nAdamant Arrow Technique: At Essence 3+, the Solar may infuse a single phantom or physical arrow per scene with her enduring Essence. So long as she lives, the arrow cannot be destroyed or pulled from the target. Such arrows can be moved by cutting away the base into which they have landed—a tree can still be cut down, a wall still reduced to rubble—but the arrow will remain inviolate. Only the Solar who fired this arrow, or one blessed with her permission, may remove it from its resting place.", :category :charm, :prereq-charms "None", :ability :archery, :name "Phantom Arrow Technique", :keywords "None", :type :supplemental, :duration "Instant", :page 257, :min-ability 3, :cost "1m", :min-essence 1}
                     {:description "Charging her arrow with Essence, the Exalt fires a heavy shot that rends the air as it passes onto her target, lighting the arrow on fire. If the arrow strikes flammable materials, a violent blaze instantly seeks to consume the struck object. This fire is natural, and may spread to surrounding objects or cause combustible materials to explode. When used in a decisive attack against a target, it adds one automatic success to the damage roll. If the attack does at least three health levels of damage, the target catches on fire, and must contend with (Solar’s Essence) lethal dice of damage every turn until he’s able to extinguish himself.", :category :charm, :prereq-charms "Phantom Arrow Technique", :ability :archery, :name "Fiery Arrow Technique", :keywords "Decisive-only", :type :supplemental, :duration "Instant", :page 257, :min-ability 4, :cost "2m", :min-essence 1}
                     {:description "The Solar graces her shot with unerring precision and fires it along a flow of Essence, causing it to slice through the air between the arrow and its mark. Her attack ignores penalties from non-visual conditions such as high winds, bad weather, flawed ammunition, and so on. In addition, her withering attack accuracy is calculated as if it were made from short range regardless of the distance she’s firing from. With appropriate Awareness Charms, the Solar may use this Charm to make attacks from extreme long range.\n", :category :charm, :prereq-charms "Sight Without Eyes", :ability :archery, :name "There Is No Wind", :keywords "Dual", :type :supplemental, :duration "Instant", :page 257, :min-ability 5, :cost "3m", :min-essence 2}
                     {:description "Seething with remonstrative ire, the Solar palms a storm of Essence and fills the sky with demonstrative fire. With this attack, the Solar unleashes a barrage of arrows around a focus, striking up to (Essence * 3) targets up to medium range from her initial target. Roll a single attack against the defenses of every target, and then apply damage.\n\nThese extra decisive attacks carry a base damage of her Perception—divvy up her current Initiative evenly among the remaining shots to determine the total raw damage of each attack. Arrows reaching out to medium range from her initial target are expressly allowed to ignore the range limitations of her weapon without penalty. The Exalt’s Initiative does not reset until every damage roll has been completed.", :prereq-charms "Trance of Unhesitating Speed", :ability :archery, :name "Arrow Storm Technique", :keywords "Decisive-only", :type :simple, :duration "Instant", :page 257, :min-ability 5, :arrow-storm-technique-cost "5m, 1wp", :cost "5m, 1wp", :character-tags [], :min-essence 2}
                     {:description "To invite the wrath of the Lawgiver is to invoke one’s own doom. The Solar gains (Essence) automatic successes to her Join Battle result, and if she acts before her target, her first attack is unblockable. Flashing Vengeance Draw is expressly permitted to be used in combination with Charms that boost Join Battle results, so long as they are not based in Melee, Thrown, or Brawl.", :prereq-charms "Trance Of Unhesitating Speed", :ability :archery, :name "Flashing Vengeance Draw", :keywords "None", :type :supplemental, :duration "Instant", :page 258, :min-ability 5, :flashing-vengeance-draw-cost "3m", :cost "3m", :character-tags [], :min-essence 2}
                     {:description "The Lawgiver suffers no impunities; with terrific speed and ferocious import, she may answer the blades of her transgressors. When the Solar succeeds at a disengage action, she may unleash a withering or decisive Archery attack from close range, even if she has already attacked that turn. This attack must be directed at the one she broke away from.", :prereq-charms "Flashing Vengeance Draw", :ability :archery, :name "Hunter’s Swift Answer", :type :reflexive, :duration "Instant", :page 258, :keywords "Uniform", :min-ability 5, :cost "5m, 1wp", :character-tags [], :min-essence 2}
                     {:description "Honing her skill and focusing her will, the Exalt births a stunning varicolored bow from her palm. This Charm creates a weapon with stats identical to a powerbow, described on page 598. The weapon is made of solidified Essence forged in all the colors of Solar anima, and glows like a torch.\n\nFor additional purchases, players may add custom Evocations to Immaculate Golden Bow. Players should work with their Storyteller to create Evocations that fit the char\nacter’s personality or iconic anima manifestation. In addition, Immaculate Golden Bow has the following power:\n\nSky-Eater’s Crest: For four motes, Immaculate Golden Bow is transformed for a single turn, growing wings, spines, fins, or other appendages appropriate to the Exalt’s iconic manifestation, providing a barrier of heavy cover against ranged attacks.", :prereq-charms "Phantom Arrow Technique", :ability :archery, :name "Immaculate Golden Bow", :sky-eater’s-crest "For four motes, Immaculate Golden Bow is transformed for a single turn, growing wings, spines, fins, or other appendages appropriate to the Exalt’s iconic manifestation, providing a barrier of heavy cover against ranged attacks.", :type :simple, :duration "One scene", :page 258, :keywords "None", :min-ability 4, :cost "5m, 1wp", :character-tags [], :min-essence 2}
                     {:description "The Solar shoots from her heart; the arrow is part of her. As such, she can sometimes reach out and draw her Essence across an arrow in flight, causing it to flash and flare, surging toward its target like a smite from the sun. This Charm can only be activated on an attack supplemented by Fiery Arrow Attack; when the attack generates at least one 10, this Charm adds one automatic success to the attack, and for each 10 in the attack roll it adds one die to the attack’s raw damage. As the name suggests, Dazzling Flare Attack goes off like a spectacular flare that can be seen for miles—every target using shadows for cover within two range bands must roll Stealth, with a -2 success penalty to the attempt, or be revealed.", :prereq-charms "Fiery Arrow Attack", :ability :archery, :name "Dazzling Flare Attack", :type :reflexive, :duration "Instant", :page 258, :keywords "Decisive-only", :min-ability 5, :cost "3m", :character-tags [], :min-essence 2}
                     {:description "Clearing her mind of all thoughts, the Solar focuses only on the arrow drawn back against her bowstring, feeling for the flow of Essence she needs to make an incredible shot. The Solar must take a special “long aim” action—an aim action lasting three rounds—against a single target in order to use this Charm. Invoking Seven Omens Shot converts the normal +3 bonus dice from aiming into three automatic non-Charm successes and adds any extra successes on the attack roll to the attack’s raw damage. Accuracy Without Distance can shorten the action by a single round, but may only add a single non-Charm success for each round shortened. Killing an opponent with this Charm awards the Solar one point of Willpower.", :prereq-charms "Accuracy Without Distance", :ability :archery, :name "Seven Omens Shot", :type :simple, :duration "Instant", :page 255, :keywords "Decisive-only", :min-ability 5, :cost "3m, 1wp", :character-tags [], :min-essence 3}
                     {:description "Holding arrows between each finger, the Solar draws down on her target, firing with profound speed and focus. The Solar may draw and attack a single target repeatedly, launching multiple withering attacks until she either misses or crashes her opponent. Revolving Bow Discipline can only be used within short or close range, and can’t be used on targets already in crash. Used against a battle group, the Solar attacks until she misses or depletes the group’s Magnitude.\n\nAt Essence 4+, the Solar gains one point of temporary Willpower when she crashes a foe with this attack.", :prereq-charms "Arrow Storm Technique", :ability :archery, :name "Revolving Bow Discipline", :type :simple, :duration "Instant", :page 259, :keywords "Perilous, Withering-only", :min-ability 5, :cost "6m, 1wp", :character-tags [], :min-essence 3}
                     {:description "With instincts honed for the kill, the Exalt feels the momentum of battle break and flee her target. When an opponent within range suffers crash, the Lawgiver draws on this moment to attack again, even if she has already used a combat action that turn. This attack requires no aim action, but if she wishes to use Finishing Snipe, the Lawgiver must not be engaged in a Simple action that would prevent her from attacking.", :prereq-charms "Hunter’s Swift Answer", :ability :archery, :name "Finishing Snipe", :type :reflexive, :duration "Instant", :page 259, :keywords "Decisive-only", :min-ability 5, :cost "7m", :character-tags [], :min-essence 3}
                     {:description "The Lawgiver hones her killing prowess, splitting an arrow into a devastating barrage. The Exalt only needs a single arrow to fire this shot; her one arrow splits into multiple arrows and all are directed against a single target. The Solar may split her shot into a maximum of (Dexterity) arrows. If the attack hits, each created arrow hits with a raw damage equal to the Solar’s current Initiative minus her successes on each damage roll. Therefore, if she rolls 10 damage dice and gains two successes on the first roll, the second roll will feature eight damage dice. If that gains four successes, her third damage roll will be four dice. If the Exalt runs out of damage dice due to successful hits, her created arrows cannot do less than (Essence) damage each.", :prereq-charms "Phantom Arrow Technique", :ability :archery, :name "Rain of Feathered Death", :type :simple, :duration "Instant", :page 259, :keywords "Decisive-only", :min-ability 5, :cost "3m per duplicate, 1wp", :character-tags [], :min-essence 3}
                     {:description "During combat, if the Lawgiver’s Awareness check uncovers an opponent, she may make an attack against that opponent regardless of the Initiative order, without using her attack action for the round, and without having to use an aim action. The Solar may pay to use this Charm multiple times to attack multiple opponents she has uncovered in a single Awareness check.", :prereq-charms "Dazzling Flare Attack", :ability :archery, :name "Shadow-Seeking Arrow", :type :reflexive, :duration "Instant", :page 259, :keywords "Uniform", :min-ability 5, :cost "3m, 2i", :character-tags [], :min-essence 3}
                     {:description "The Lawgiver fires an arrow that courses with burning Essence, streaking down like a falling star to explode at her enemy’s feet. This attack is a difficulty 3 gambit that requires no aim action. However, if the Exalt aims before using the Charm, she may act first on the next round, regardless of her place in the Initiative order. If another character uses magic to act first on the same round, compare their Initiative to determine order of actions. The Initiative roll on this gambit is made with double 9s. If successful, it blasts the target out of position, forcing him to act (2 + extra successes on the gambit’s Initiative roll) ticks later than he would have. If Searing Sunfire Interdiction drops the target to a tick of 0 or less, he loses his turn for the round. Searing Sunfire Interdiction cannot be used on the same target twice consecutively.\n\nAn Essence 3+ repurchase of this Charm lowers the difficulty of the gambit to 2 and waives the Initiative cost upon success. \n\nAn Essence 4+ repurchase of the upgraded Charm resets the Solar’s attack if she drops an opponent from a higher Initiative tick to a lower Initiative tick than her own.\n\nAn Essence 5+ repurchase of the second upgrade allows the Solar to use Searing Sunfire Interdiction twice consecutively on the same target, dropping the Willpower cost from the second shot. If the Solar delays her opponent with both shots, he’s also forced backwards a range band, even if this would force him off a cliff or a rooftop. \n\nAn Essence 6+ repurchase of the previous upgrade allows the Lawgiver to use this gambit repeatedly against a single target: each time she successfully hits with this gambit, she may immediately fire the gambit again, so long as she has ammunition. If she misses or forces her target to lose a turn, the Charm ends. As with the previous upgrade, waive the willpower cost from all but the first shot. If the Solar stops an opponent from acting, award her a point of Willpower. As above, for every two shots the opponent is delayed, he’s forced back a range band. \n\nAn Essence 6+ repurchase of the previous upgrade allows the Solar to immediately target a new opponent with the above effect upon dropping another opponent to tick 0 or lower with Searing Sunfire Interdiction. ", :prereq-charms "Dazzling Flare Attack", :ability :archery, :name "Searing Sunfire Interdiction", :type :simple, :page 259, :keywords "Decisive-only", :min-ability 5, :cost "4m, 1i, 1wp", :character-tags [], :min-essence 3}
                     {:description "The Lawgiver draws a blazing bolt of Essence across her bow and fires it. The attack ignores the range of her weapon, and can be made from medium or long range without an aim action, or extreme range with an aim action. The Exalt must have higher Initiative than her target to use this attack; the conjured Spike does not use the Solar’s Initiative to do damage, but instead has a raw damage equal to her current temporary Willpower multiplied by one or the rating of any Intimacy she is trying to uphold or protect. Solar Spike is incompatible with Fiery Arrow Attack and Rain of Feathered Death, and does not reset the Exalt’s Initiative to base on a hit. Solar Spike may only be used once per scene, but can be reset by landing a withering attack with six 10s rolled across the attack and damage rolls. ", :prereq-charms "Dazzling Flare Attack", :ability :archery, :name "Solar Spike", :type :simple, :duration "Instant", :page 260, :keywords "Decisive-only", :min-ability 5, :cost "5m, 1wp", :character-tags [], :min-essence 3}
                     {:description "The Solar’s judgment scourges her target with devouring flames. She may only pay to use this attack when unleashing Solar Spike, and when her anima is at bonfire. Instead of conjuring Solar Spike, the Solar draws her anima as if she were pulling an arrow from a quiver, her iconic manifestation taking the form of a living, screaming missile. This attack follows the rules of Solar Spike, but adds the Solar’s Initiative to the raw damage of the attack. This does cause the Lawgiver’s Initiative to reset on a hit, but if Heart-Eating Incineration kills her target, the target’s body and soul are engulfed in a torrent of flames and burned away completely, restoring a number of motes to the Solar equal to her Intimacy rating for the target plus his permanent Essence score. Using Heart-Eating Incineration resets the Solar’s anima to the dim level. Spirits destroyed with this attack may still reform as they normally might.", :prereq-charms "Solar Spike", :ability :archery, :name "Heart-Eating Incineration", :type :reflexive, :duration "Instant", :page 260, :keywords "Decisive-only", :min-ability 5, :cost "3m, 3a", :character-tags [], :min-essence 3}
                     {:description "The Lawgiver may use this Charm to shorten the long aim action of Seven Omens Shot by one round, forfeiting the prerequisite’s automatic non-Charm successes to make the attack faster. An Essence 5+ repurchase allows the Solar to add the lost successes back into the attack.", :prereq-charms "Seven Omens Shot", :ability :archery, :name "Dust and Ash Sleight", :type :reflexive, :duration "Instant", :page 260, :keywords "Decisive-only", :min-ability 5, :cost "3m", :character-tags [], :min-essence 4}
                     {:description "When the Lawgiver is cornered and fighting for her life, the burning power of her judgment becomes even more terrifying. Drawing the burning Essence of her life from her very wounds, she can unleash a powerful, Essence laden shot from her bow that can override other attacks and overwhelm her attackers. The Solar may use this Charm to clash attacks against her from short or close range, but only when she is in her -4 health levels. This clash gains (Essence) automatic successes, and the damage roll doubles 9s. However, Initiative damaged by this roll is not transferred to the Solar; it is instead rerolled as decisive damage against her target, ignoring hardness and doubling 10s.\n\nAn Essence 5+ repurchase of this Charm removes the Perilous keyword, allowing the Solar to spend herself into lower negative Initiative numbers while crashed.", :prereq-charms "Revolving Bow Discipline", :ability :archery, :name "Heavens Crash Down", :type :reflexive, :duration "Instant", :page 260, :keywords "Clash, Perilous, Withering-only", :min-ability 5, :characters-at-medium-or-long-range-must-typically-take-an-aim-action-before-they-can-attack.-but-this-is-not-always-true.-a-character-does-not-need-to-aim-if "• She is casting a spell. • She is using a Charm from an Ability or martial art  that is not typically ranged to create a ranged attack. Examples", :cost "6m, 2i, 1wp", :character-tags [], :min-essence 4}
                     {:description "The Lawgiver feels the channels of her bow open when her prey falls into peril. This Charm allows the Exalt to fire on a crashed target from medium or long range without using an aim action.", :prereq-charms "Finishing Snipe", :ability :archery, :name "Streaming Arrow Stance", :type :simple, :duration "One scene", :page 261, :keywords "None", :min-ability 5, :cost "6m", :character-tags [], :min-essence 4} {:description "After using an aim action, the Solar may use this Charm to charge her shot with wrathful Essence, adding (Essence) damage to the attack.", :prereq-charms "Streaming Arrow Stance", :ability :archery, :name "Whispered Prayer of Judgment", :type :supplemental, :duration "Instant", :page 255, :keywords "Uniform", :min-ability 5, :cost "1m", :character-tags [], :min-essence 5}])

(def athletics-charms [{:description    "The Solar draws Essence through her pores and into her bones, suffusing and lightening her form and steadying her step. For the rest of the scene, she has perfect balance, and can stand or run on things too narrow or weak to support her normally, with no chance of falling or breaking through. She can run on a guy wire, stand on a crumbling parapet, balance on the tip of a pine tree, and perform many similar feats without needing to roll (Dexterity + Athletics).", :prereq-charms  "None", :ability        :athletics, :name           "Graceful Crane Stance", :type           :reflexive, :duration       "One Scene", :page           "261", :keywords       "None", :min-ability    1, :cost           "3m", :character-tags [], :min-essence    1}
                       {:description    "The Exalt leaps with the speed and grace of a striking hawk. Using this technique, a Solar may automatically leap forward or straight up one range band. A Solar using this Charm can easily leap to the top of a twenty foot wall or cross a Nexus street over rooftops, without having to roll. This Charm counts as the Solar’s movement for the turn. If the Solar continues to leap to a different range band each turn, the cost is reduced to one mote after the first activation.", :prereq-charms  "None", :ability        :athletics, :name           "Monkey Leap Technique", :type           :supplemental, :duration       "Instant", :page           261, :keywords       "None", :min-ability    2, :cost           "2m", :character-tags [], :min-essence    1}
                       {:description   "The Solar draws remarkable strength from deep within her core. For every three motes of Essence or Initiative the Exalt spends, her Strength score increases by one. Each dot of increase also raises the base damage of her decisive attacks by one. The Solar’s Strength cannot be increased by more than her Essence rating through use of this Charm, and this Charm may not grant her more than double her Strength score. Through use of Increasing Strength Exercise, Solars can reach the Strength minimums required to attempt certain feats of strength (p. 229).", :category      :charm, :prereq-charms "None", :ability       :athletics, :name          "Increasing Strength Excercize", :type          :simple, :duration      "One Scene", :page          262, :keywords      "", :min-ability   3, :cost          "3m or 3i", :min-essence   1}
                       {:description    "Fearless in combat, the Solar leaps over her stunned opponent. At close range, if the Exalt has higher Initiative (before cost) than her foe, she may use this Charm on her turn, rolling Dexterity + Athletics against her opponent’s Evasion. If successful, she leaps over her target, creating an opening, and may make a surprise attack (see p. 203) overhead or at their back. This Charm may only be used once per combat, but is reset by landing a decisive attack and building Initiative to 6+.", :prereq-charms  "Graceful Crane Stance, Monkey Leap Technique", :ability        :athletics, :name           "Foe-Vaulting Method", :type           :reflexive, :duration       "Instant", :page           "", :keywords       "None", :min-ability    2, :cost           "3i", :character-tags [], :min-essence    1}
                       {:description    "Like a flashing bolt, the Exalt streaks toward her goal, trailing streamers of anima. This Charm can be used to enhance a rush action (see p. 197). The Exalt moves with terrific speed—add one automatic success and reroll all 5s and 6s until 5s and 6s fail to appear. Lightning Speed can also be used each interval of a foot race or other test of speed (see p. 189).", :prereq-charms  "None", :ability        :athletics, :name           "Lightning Speed", :type           :supplemental, :duration       "Instant", :page           262, :keywords       "None", :min-ability    3, :cost           "3m", :character-tags [], :min-essence    1}
                       {:description    "Racing against herself, the Solar exults in leaving her competitors behind. In a test of speed, each interval in which the Solar accrues more successes than her fastest opponent garners a spirit-restoring surge: two motes to be used on Athletics Charms on her next turn, or two Initiative.", :prereq-charms  "Lightning Speed", :ability        :athletics, :name           "Winning Stride Discipline", :type           :permanent, :duration       "Permanent", :page           262, :keywords       "None", :min-ability    4, :cost           "—", :character-tags [], :min-essence    1}
                       {:description    "The Solar magnifies her physical Essence, increasing her ability to move massive loads. This Charm supplements an attempt to lift or break something, allowing the Solar to attempt an action with a prerequisite beyond her current Strength rating. Pay two motes and roll the Exalt’s (Strength + Athletics) as normal, converting each three successes into a dot of Strength as needed, until the Solar meets the prerequisite. This bonus Strength does not enhance her current dice pool, as this momentary surge of might only establishes whether she can succeed with her current dice. Note that she must still have enough successes remaining, after increasing her Strength, to meet the difficulty requirement of the feat.", :prereq-charms  "Increasing Strength Exercise", :ability        :athletics, :name           "Ten Ox Meditation", :type           :supplemental, :duration       "One Feat", :page           262, :keywords       "None", :min-ability    5, :cost           "2m, 3 successes per dot", :character-tags [], :min-essence    1}
                       {:description    "The Exalt draws down on the Essence around her, pulling it through her upper body, her lungs, her core and down into her legs, and then explodes skyward, rising in a brilliant, Essence-laden arc. This Charm supplements a nonranged attack which can be made against aerial targets up to short range, or ground targets at another range band. The Solar leaps at her target, striking with incredible force— damage is doubled after it is rolled. If the Exalt uses this attack to move to another range band, it counts as her movement action for the round. After striking an aerial opponent, the Exalt may fall one range band without taking damage. Thunderbolt Attack Prana is expressly permitted to be used in conjunction with Charms of other Abilities, and it is suggested that the player use it to create a signature attack that fits the character’s attitude and style.", :prereq-charms  "Increasing Strength Exercise, Monkey Leap Technique", :ability        :athletics, :name           "Thunderbolt Attack Prana", :type           :supplemental, :duration       "Instant", :page           "", :keywords       "Decisive-only", :min-ability    3, :cost           "4m, 1wp", :character-tags [], :min-essence    1}
                       {:description    "Lightening her step and balancing carefully, the Exalt may run across fluid surfaces. She may dash over unstable surfaces as if they were solid and move over surfaces no thicker than rice paper without breaking through. At full speed, she may also move across lava or other dangerous surfaces without getting hurt. This effect lasts until the Exalt stops dashing. As long as she is moving at a quick pace, she need not pay the activation cost again. At Athletics 5, Essence 2+, the Exalt can pause on unstable surfaces without breaking through, changing the duration of this Charm to “one stunt.” She can walk slowly across the surface of a still pond, pause on the crumbling parapet of a castle to give a speech, and so on. This means if she’s using the Charm to dash across the water to reach a boat, then decides to pause on the water’s surface to address the captain, she must use the Charm twice. If the Exalt is still standing on an unstable surface and is unwilling or unable to renew Feather Foot Style, she becomes subject to the normal laws of gravity and buoyancy. Also note: while she may safely dash across a caustic or burning surface, standing on top of lava and other dangerous surfaces will cause harm.", :prereq-charms  "Graceful Crane Stance, Lightning Speed", :ability        :athletics, :name           "Feather Foot Style", :type           :reflexive, :duration       "Until the Exalt stops running", :page           263, :keywords       "Mute", :min-ability    3, :cost           "3m", :character-tags [], :min-essence    1}
                       {:description    "With speed and balance heightened to the Nth degree, the Solar’s Essence may bond with a surface, allowing her to run up walls or stand upside down on horizontal surfaces such as tree branches, bridge bottoms or overhangs, or to lay flat against a ceiling looking down at her prey. Like Feather Foot Style, if the Solar is unable or unwilling to renew this effect, her preternatural grip dwindles and she may plummet and be subject to falling damage. Spider Foot Style’s effect can be extended for one round by a well described stunt during a turn in which the Charm is active.", :prereq-charms  "Feather Foot Style", :ability        :athletics, :name           "Spider Foot Style", :type           :reflexive, :duration       "(Essence+1) turns", :page           "", :keywords       "Mute", :min-ability    4, :cost           "3m", :character-tags [], :min-essence    1}
                       {:description    "It is the Solar’s nature to rise above. Meditating on the tyrannical bonds of gravity, the Exalt learns to separate her Essence from that which pulls her down. By paying two extra motes to the activation of Soaring Crane Leap, the Exalt may drift across a horizontal range band without initial thrust, allowing her to plane along low ceilings or avoid traps that might detect a more wild leaping motion. In addition, she can use this Charm on each round after activating Soaring Crane Leap to continue to glide across range bands without dropping down.", :prereq-charms  "Soaring Crane Leap", :ability        :athletics, :name           "Unbound Eagle Approach", :type           :permanent, :duration       "Permanent", :page           264, :keywords       "None", :min-ability    4, :cost           "—(2m)", :character-tags [], :min-essence    2}
                       {:description    "Meditating on the frozen moment, the Lawgiver sees the universe aligning around the neck of her target. Through strength, balance and control, she pulls at the distance between herself and her foe, and flashes in for the kill. The Exalt may use this Charm as far away as medium range, to instantly flash past her opponent, striking him at close range. If her attack is withering, it deals double damage after soak, but before damage is rolled. If it is decisive, it adds her Essence score to the base damage of the attack. As the Solar slides past her opponent, she ends the attack standing at close range. This counts as the character’s movement for the round. In order to use this Charm, the Solar must be at higher Initiative than her opponent, and at 6+ Initiative. Leaping Tiger Attack is explicitly allowed to be used in combination with the Charms of other Abilities, but is incompatible with Thunderbolt Attack Prana and Eagle-Wing Style.", :prereq-charms  "Graceful Crane Stance, Lightning Speed", :ability        :athletics, :name           "Leaping Tiger Attack", :type           :supplemental, :duration       "Instant", :page           264, :keywords       "Dual", :min-ability    5, :cost           "4m, 1wp", :character-tags [], :min-essence    2}
                       {:description    "Attuned to Essence currents that flow through the world, the Solar moves as if in a waking dream. She travels in flashing sprints and sparking leaps, moving from branch to branch like a skipping stone and leaving dust clouds in her wake. This Charm lasts one hour. During this hour, the Solar moves up to three range bands per turn, depending on the terrain and her ability to move at an uninterrupted clip. If she joins battle, her speed is greatly slowed, as she must focus more completely on her environment. The Solar resumes moving one range band per turn, but the Charm still has an effect: double 9s on rush attempts, and for every 10 rolled on a rush, the Solar gains a point of Initiative. If the Exalt knows the Charm Triumph-Forged God-Body, the rushes instead gain (Essence) bonus dice. These benefits also apply to each interval of a test of speed. If the Lawgiver chooses to renew this technique at the end of an hour, ignore the Willpower cost.", :prereq-charms  "Lightning Speed", :ability        :athletics, :name           "Racing Hare Method", :type           :reflexive, :duration       "One Hour", :page           264, :keywords       "None", :min-ability    4, :cost           "5m, 1wp", :character-tags [], :min-essence    2}
                       {:description    "The Solar learns to channel the exhilaration she feels at chasing an opponent into a burst of adrenal power that restores her spirit. On successfully rushing an opponent, the Exalt gains three motes to be used on Athletics Charms. These motes last until she has taken her next turn. ", :prereq-charms  "Lightning Speed", :ability        :athletics, :name           "Onrush Burst Method", :type           :permanent, :duration       "Permanent", :page           264, :keywords       "None", :min-ability    3, :cost           "—", :character-tags [], :min-essence    2}
                       {:description    "The Solar trains her body to feel the Essence of those she would outrun, matching their strength with her stride. When she falls behind in a test of speed, every 10 her fastest opponent rolls also counts as a single success to the Solar’s own roll. This Charm also functions in rushes, to aid in countering the target’s attempts to avoid the Solar. ", :prereq-charms  "Winning Stride Discipline", :ability        :athletics, :name           "Arete-Driven Marathon Stride", :type           :permanent, :duration       "Permanent", :page           264, :keywords       "None", :min-ability    5, :cost           "—", :character-tags [], :min-essence    2}
                       {:description    "Channeling her strength through her Essence, the Solar’s attacks strike harder and deeper. This Charm supplements a close range decisive attack, allowing the Solar to ignore (her Strength) hardness. Armor-Eating Strike is expressly permitted to be used in conjunction with Charms of other Abilities.", :prereq-charms  "Increasing Strength Exercise", :ability        :athletics, :name           "Armor-Eating Strike", :type           :supplemental, :duration       "Instant", :page           "", :keywords       "Decisive-only", :min-ability    3, :cost           "1m", :character-tags [], :min-essence    2}
                       {:description    "Through intense muscle control, the Solar’s insides erupt with surging Essence power. Reroll all non-successes on a feat of strength.", :prereq-charms  "Increasing Strength Exercise", :ability        :athletics, :name           "Thunder’s Might", :type           :reflexive, :duration       "Instant", :page           265, :keywords       "None", :min-ability    5, :cost           "5m", :character-tags [], :min-essence    2}
                       {:description    "The Solar gathers enormous spiritual pressure into her legs and launches herself skyward. The Exalt makes a wild leap four range bands forward or three straight up. As the force of her leap is almost uncontrolled, she may not leap fewer than three range bands with this Charm. This Charm stays active every turn until the Solar stops leaping across range bands, making it possible for the Exalt to cross a mountain range in minutes. If this Charm is combined with Monkey Leap Technique, the Exalt can make a controlled leap to the second range band. If opponents are within close range before the Exalt activates this Charm, she must succeed at a disengage action before it can be activated. All minor opponents within close range when the Solar uses this Charm suffer automatic knockdown, and more impressive opponents may need to roll to keep their balance.", :prereq-charms  "Unbound Eagle Approach", :ability        :athletics, :name           "Mountain-Crossing Leap Technique", :type           :simple, :duration       "Until the Exalt stops leaping", :page           265, :keywords       "None", :min-ability    5, :cost           "7m, 1wp", :character-tags [], :min-essence    3}
                       {:description    "Focusing her Essence down her spine and through her lower extremities, the Exalt repels the ground with a tremendous leap. The Exalt locks onto an aerial target, whether it be a Haslanti skyship or a Stormwind Rider, leaps toward it and begins to soar. This moves her up to two range bands, expending her movement action, and allows her to continue flying one range band through the air on subsequent turns by paying two motes or two Initiative per turn. Once she is within combat range of an opponent, attacking is sufficient enough movement to keep her airborne. If she is a ranged fighter, she may also use Unbound Eagle Approach, paying two motes in order to hang in the air, planing along an air current as she takes an aim action. Lastly, the Solar can also channel a burst of speed for two motes, allowing her to rush or disengage from appropriate distances. If she fails to activate the Charm, gets knocked off-course or otherwise begins to fall, Eagle-Wing Style cannot be reactivated until she touches down and is able to leap again. Eagle-Wing Style can be activated at the apex of Mountain-Crossing Leap Technique, in which case it costs only four motes to activate.", :prereq-charms  "Mountain-Crossing Leap Technique", :ability        :athletics, :name           "Eagle-Wing Style", :type           :reflexive, :duration       "Indefinite", :page           265, :keywords       "None", :min-ability    5, :cost           "5m, 1wp", :character-tags [], :min-essence    3}
                       {:description    "A Solar with this Charm can attempt a rush from medium range. If successful, she will automatically move one range  and closer to her target on his next two turns, in addition to her normal movement", :prereq-charms  "Racing Hare Method", :ability        :athletics, :name           "Demon-Wasting Rush", :type           :supplemental, :duration       "Instant", :page           265, :keywords       "None", :min-ability    5, :cost           "5m, 1wp", :character-tags [], :min-essence    3}
                       {:description    "Like a living storm, the Exalt gathers momentum and speed as she races over land. In combat, the Exalt may spend Initiative for successes to rush a target. In a test of speed she may use it at each interval.", :prereq-charms  "Arete-Driven Marathon Stride", :ability        :athletics, :name           "Hurricane Spirit Speed", :type           :supplemental, :duration       "Instant", :page           265, :keywords       "None", :min-ability    5, :cost           "1i per success", :character-tags [], :min-essence    3}
                       {:description    "The Exalt projects herself forward on a pulse of Essence, faster than a heartbeat, moving like a blur. The Exalt may attempt a rush against an opponent up to three range bands away. If successful, she flashes out in a burst of speed, and flashes in at close range to her target that same instant. This Charm removes the flurry penalty for an attack made after a rush. If used in conjunction with Racing Hare Method, the Exalt can rush an opponent up to four range bands distant.", :prereq-charms  "Arete-Driven Marathon Stride, Racing Hare Method", :ability        :athletics, :name           "Godspeed Steps", :type           :reflexive, :duration       "Instant", :page           "", :keywords       "None", :min-ability    5, :cost           "4m, 1wp", :character-tags [], :min-essence    3}
                       {:description    "The Exalt’s body is momentarily framed with surging power. This Charm supplements a feat of strength, adding (Strength) non-Charm bonus dice to the attempt. This is explicitly compatible with the bonus granted by Increasing Strength Exercise.", :prereq-charms  "Thunder’s Might", :ability        :athletics, :name           "Power Suffusing Form Technique", :type           :supplemental, :duration       "Instant", :page           266, :keywords       "None", :min-ability    5, :cost           "4m", :character-tags [], :min-essence    3}
                       {:description   "Striving toward physical and spiritual perfection, the Solar is an exemplar of physical might. When performing feats of strength, the cost of the Athletics Excellency is permanently reduced to one mote per two dice.", :category      :charm, :prereq-charms "Power Suffusing Form Technique", :ability       :athletics, :name          "Legion Aurochs Method", :type          :permanent, :duration      "Permanent", :page          266, :keywords      "None", :min-ability   5, :cost          "-", :min-essence   3}
                       {:description    "The Solar possesses a body and spirit intensified by thousands of hours of vigorous exercise and meditation. This Charm applies the double 9s rule to every Athletics roll.", :prereq-charms  "Arete-Driven Marathon Stride,", :ability        :athletics, :name           "Triumph-Forged God-Body", :type           :permanent, :duration       "Permanent", :page           "266", :keywords       "None", :min-ability    5, :cost           "—", :character-tags [], :min-essence    3}
                       {:description    "Once per scene, the Exalt may take a second movement action on her turn.", :prereq-charms  "Godspeed Steps", :ability        :athletics, :name           "One Extra Step", :type           :permanent, :duration       "Permanent", :page           "266", :keywords       "None", :min-ability    5, :cost           "—", :character-tags [], :min-essence    4}
                       {:description    "Relentless in pursuit of her ideals, the Lawgiver’s anima becomes like a pair of burning wings that carry her across the sky. When using Eagle-Wing Style to engage in aerial combat, and when her anima is at the bonfire level, the Solar’s attacks benefit from the effects of Onrush Burst Method, generating motes that can be used to pay the activation costs of Athletics Charms. When in use, the Solar’s anima typically resolves into wings that resemble an eagle’s or something else appropriate to the Solar’s iconic manifestation.", :prereq-charms  "Eagle-Wing Style, Onrush Burst Method", :ability        :athletics, :name           "Bonfire Anima Wings", :type           :permanent, :duration       "Permanent", :page           "266", :keywords       "None", :min-ability    5, :cost           "—", :character-tags [], :min-essence    4}
                       {:description   "The Solar’s might is permanently enhanced, lowering the difficulty of all feats of strength by two.", :category      :charm, :prereq-charms "Living Wind Approach", :ability       :athletics, :name          "Aegis of Unstoppable Force", :type          :supplemental, :duration      "Permanent", :page          266, :keywords      "None", :min-ability   5, :cost          "-", :min-essence   4}
                       {:description    "Once per scene, the Solar may reflexively channel a burst of impossible speed to automatically succeed at a rush. In a test of speed, she may use this to generate one more success than her opponent on any one interval. If multiple Solars use this on the same interval, they all assume a result one greater than the highest number of successes.", :prereq-charms  "One Extra Step", :ability        :athletics, :name           "Living Wind Approach", :type           :permanent, :duration       "Permanent", :page           "266", :keywords       "None", :min-ability    5, :cost           "—", :character-tags [], :min-essence    5}
                       {:description    "Summoning the might of untold forces, the Exalt crosses the threshold of legend. This Charm is the gateway to outrageous shows of physical prowess—the Solar gains double 7s to attempt a feat of strength, and she counts as meeting its Strength prerequisite (p. 229) no matter how high that requirement might be.", :prereq-charms  "Aegis of Unstoppable Force", :ability        :athletics, :name           "Nine Aeons Thew", :type           :supplemental, :duration       "Instant", :page           "", :keywords       "None", :min-ability    5, :cost           "1m, 1wp", :character-tags [], :min-essence    5}])

(def athletics-miracles [{:description    "A Solar who has used the prerequisite to increase her Strength to the limit is sufficiently strong enough to hurl a human-sized ally forward or up one range band. This Charm uses the Solar’s own movement action for the round. If the Solar has learned Power Suffusing Form Technique (see Exalted, p. 266), she can combine that Charm with this to hurl an ally the size of a horse and rider safely up or forward one range band, or she may toss a human-sized ally forward two range bands. This use adds one Willpower to the cost of this Charm, but drops the mote cost to two.", :prereq-charms  "Increasing Strength Exercise", :ability        :athletics, :name           "Strength-Hying Heave", :type           :reflexive, :duration       "Instant", :page           "", :keywords       "None", :min-ability    4, :cost           "4m", :character-tags [], :min-essence    1}
                         {:description    "Like the Unconquered Sun, the Solar is everywhere and nowhere at once. Moving at impossible, Essence-fueled speeds, the Solar becomes multiple copies of herself. As long as she keeps moving, she is each of her copies and none of them at the same time. The Lawgiver becomes a battle group having Size (Essence / 2 rounded up), Magnitude 10 (regardless of her maximum Health Levels), and no bonuses from Drill or Might — simply use the Solar’s normal combat pool. This Charm is incompatible with heavy armor, and incompatible with all Resistance Charms except those which are Permanent-type or Simple-type Charms which were activated before using Faster than Self Technique. Nor can the Solar benefit from giving her “battle group self” enhanced abilities through the use of War Charms. Each round this Charm is active costs the Solar an additional mote of Essence to keep active. In addition, when the Solar’s Magnitude track fills up with damage and she loses a point of Size, instead of a rout check she is subject to a difficulty 3 Stamina + Athletics roll to maintain the Charm. Ending this Charm gives the Exalt a -1 success fatigue penalty to all of her Athletics rolls for the next three rounds. Faster than Self Technique can only be activated once per scene. ", :prereq-charms  "Living Wind Approach, Hurricane Spirit Speed", :ability        :athletics, :name           "Faster than Self Technique", :type           :simple, :duration       "One Scene", :page           "", :keywords       "Perilous", :min-ability    5, :cost           "10m, 1wp (+1m per round)", :character-tags [], :min-essence    5}])

(def awareness-charms
               [{:description "A breath of Essence seals the five senses into a more perfect form. The Solar’s senses are heightened and attuned to minute motions and sounds, dim and noisy conditions. She can differentiate between subtle tastes and textures with only the slightest variation. Thus sharpened, it is more difficult for characters to escape her notice, or to deceive her hunting senses. For the rest of the scene, the Exalt’s Awareness rolls benefit from double 9s. If the effect of any Unsurpassed (Sense) Discipline applies, reroll 6s until they cease to appear. Use of Sensory Acuity Prana comes without the danger of sensory overload; the Charm helps the Solar manage her senses more effectively.",
                 :prereq-charms "None",
                 :ability :awareness,
                 :name "Sensory Acuity Prana",
                 :type :reflexive,
                 :duration "One scene",
                 :page 267,
                 :keywords "None",
                 :min-ability 2,
                 :cost "5m",
                 :character-tags [],
                 :min-essence 1}
                {:description "Upon learning this technique, the Solar’s senses guard her from threats she is not consciously aware of. Whenever the Solar is in danger—even if she is not consciously aware of the threat—her relevant senses will home in on the source of danger, enhancing her Awareness to make the threat known to her. Surprise Anticipation Method has two functions. First: for every 9 she rolls on an Awareness check to reveal a hidden enemy, trap, or any source of harm not readily apparent, she gains a single mote of Essence, and for every 10 she gains two. This charge of Essence can only be used to offset the cost of activating Awareness Charms to reveal a threat. Motes returned in this fashion may retroactively lower the cost committed to Awareness Charms of a scene or longer duration, both lowering the committed cost and returning the discounted mote(s) to the Solar’s mote pool. Second: her senses function even when she is asleep or Incapacitated, allowing her to use any of her Awareness Charms subconsciously. A threat revealed to the Solar while she is asleep or unconscious automatically revives her, allowing her to defend herself.",
                 :prereq-charms "Sensory Acuity Prana",
                 :ability :awareness,
                 :name "Surprise Anticipation Method",
                 :type :reflexive,
                 :duration "Instant",
                 :page 267,
                 :keywords "None",
                 :min-ability 3,
                 :cost "—",
                 :character-tags [],
                 :min-essence 1,
                 :two-functions.-first "for every 9 she rolls on an Awareness"}
                {:description "Prerequisite Charms: Sensory Acuity Prana The Solar’s visual acuity is heightened to several times that of a normal mortal. This Charm represents an array of mechanical benefits: the Solar may perform difficulty 2 or 3 sight-based actions without a roll. She gains an additional two dice to notice hidden persons or devices, to catch sleight of hand and see through disguises. In dim conditions, she sees as well as in broad daylight. Deeper visual hindrances such as dense smoke or fog represent less of a struggle: reduce the difficulty of seeing in such conditions by 1, and remove the -1 penalty to detect hidden threats in such environments. These effects reflect the Exalt’s ability to notice and process hundreds of minute details, as well as to focus and manage light sources more effectively. The Solar’s visual range is also increased: she can see tiny details at 100 yards, quickly count masses of troops, and notice threats well in advance of her position. Special activation rules: The player may choose to activate Keen Sight Technique by paying six motes, one willpower. Doing so sets the duration of this Charm to Indefinite. Despite being Simple type Charms, each Keen (Sense) Technique can be activated simultaneously by paying the full cost of each. In addition, these Charms are compatible with Sensory Acuity Prana as well as with each other.",
                 :effectively.-the-solar’s-visual-range-is-also-increased "she",
                 :less-of-a-struggle "reduce the difficulty of seeing in such",
                 :prereq-charms "Sensory Acuity Prana",
                 :ability :awareness,
                 :name "Keen Sight Technique",
                 :special-activation-rules "The player may choose to activate",
                 :type :simple,
                 :duration "One scene",
                 :page 267,
                 :keywords "None",
                 :min-ability 3,
                 :of-mechanical-benefits "the Solar may perform difficulty",
                 :cost "3m or 6m, 1wp",
                 :character-tags [],
                 :min-essence 1}
                {:description "The Iron Wolf’s gaze cannot be misdirected, and her focus cannot be dissuaded. Even the greatest feats of stealth pale before her genius eyes. When a character attempts to hide from the Solar, steal from her, or cheat her with a quick motion, revert (Essence) of his double successes—typically 10s, but 9s under the effect of double 9s and so on—to single successes. This effect can even contest magic that is considered impossible to notice. The benefit of this Charm only applies to the Solar—it is her eye which is unswerving. The player can choose to activate this Charm after the opposing roll has been made.",
                 :prereq-charms "Keen Sight Technique",
                 :ability :awareness,
                 :name "Unswerving Eye Method",
                 :type :reflexive,
                 :duration "Instant",
                 :page "",
                 :keywords "None",
                 :min-ability 4,
                 :cost "3m",
                 :character-tags [],
                 :min-essence 1}
                {:description "The Exalt’s senses of taste and smell are capable of flawless identification of flavors, textures, and scent profiles. This Charm represents an array of mechanical benefits,
                as well as two distinct functions of the senses taste and smell. The Solar can recognize an individual by scent alone, and she can tell older scents from new ones, enabling her to tell how recently an individual was present. Add +2 successes to Survival rolls to hunt for food, track a character, or find water, using her sense of smell. This Charm automatically extends the range of these actions to (Essence * 200) yards. This Charm also creates a library of scents which your character can reference. Upon learning this Charm, the library is populated with the scents of any Major or Defining Intimacy the character may have, but it can also include scents outside the confines of intimacies if the Storyteller deems them reasonable, including any scent the character has encountered in the last 24 hours, the smell of a favorite food or drink, or scents linked to strong memories such as love or pain. Entries in a Solar’s scent library can be used to aid in Investigation and Survival rolls, as well as in the smell-based Awareness Charms further up the tree. This Charm also creates a taste index. Similar to the scent library, the taste index allows the Exalt to immediately recognize any taste she has experienced within the realm of reason. The Solar can identify obscure, complex, or similar flavors and she can deconstruct a meal she has eaten to its basic ingredients, so long as she has experienced most of the flavors at some point in time. The taste index isn’t populated the same way as the scent library; most characters do not have Major or Defining intimacies for flavors. Rather, the Solar may perfectly recognize any flavor the Storyteller considers reasonable. If the character has been a master chef all of her life, her palate is going to be considerably more robust than that of an islander with little contact with the outside world. Conversely, those who have lived or traveled in remote locations may have had access to rare and exotic food, drink, and poison. This Charm follows the special activation rules of Keen Sight Technique (p. 267).",
                 :prereq-charms "Sensory Acuity Prana",
                 :ability :awareness,
                 :name "Keen Taste and Smell Technique",
                 :type :simple,
                 :duration "One scene",
                 :page "",
                 :keywords "None",
                 :min-ability 3,
                 :cost "3m or 6m, 1wp",
                 :character-tags [],
                 :min-essence 1}
                {:description "The Solar’s sense of taste is so intense that she can analyze the emotions that went into preparing a meal or beverage. In a bit of overcooked meat, she might sense the cook’s turmoil; that his mind is not on his work. In a sip of soup salted with arsenic, she might sense the cool, murderous intent of one who is not her normal chef. This Charm acts as an automatically successful read intentions action to determine the emotional state of the one who prepared a meal or poured a drink. The Solar need only sample a single bite of a meal or take a single sip of a drink to gain this understanding.",
                 :prereq-charms "Keen Taste and Smell Technique",
                 :ability :awareness,
                 :name "Genius Palate Summation",
                 :type :simple,
                 :duration "Instant",
                 :page "269",
                 :keywords "None",
                 :min-ability 3,
                 :cost "2m",
                 :character-tags [],
                 :min-essence 1}
                {:description "The keen nose of the Iron Wolf seeks out those who would attempt to hide. Before an Awareness roll to detect unseen characters, the Solar’s nose automatically counts heads, telling her how many people are in the room, or are within medium range of her. If any scents belong to a person in her scent library, she automatically identifies him. For any unknown, she can further make generally accurate discernments about what kind of being each scent belongs to. Beasts, for example, smell different than humans, as do the undead and spirits. If a scent is not in her library, she can still form a general idea about the creature it belongs to. At this point, the player can choose to pay two motes to enhance the Lawgiver’s sense of smell, aiding her in scenting the direction and distance of each target. This adds one automatic success to an Awareness roll to uncover hidden targets, and to Join Battle if necessary. At Awareness 5+, Essence 3+, the Solar can detect dematerialized spirits with this Charm.",
                 :prereq-charms "Keen Taste and Smell Technique",
                 :ability :awareness,
                 :name "Foe-Scenting Method",
                 :type :reflexive,
                 :duration "Instant",
                 :page "269",
                 :keywords "None",
                 :min-ability 4,
                 :cost "0m or 2m",
                 :character-tags [],
                 :min-essence 1}
                {:description "The Lawgiver listens with the intensity of an owl, and feels movement in the world like a spider feels a touch against its web. The Exalt may identify fabrics and minerals she knows with a cursory touch, and can hear at frequencies several times lower than a human. She can listen clearly to conversations through thick stone walls, hear creatures burrowing in the ground, ants marching on the branches above her head, and other, similar feats. For many actions that would require success on a roll at difficulty 2, the Solar can succeed without a roll. For more difficult actions, the difficulty is lowered by 1, and the Solar gains one automatic success. If she has a specialty that can be logically applied to the roll, the difficulty drops to 1. For example, a Solar who is unfamiliar with art crime will find it more difficult to identify a faked painting by touch than a Solar with an Investigation specialty in detecting forgeries. These benefits do not apply to detecting opponents in stealth. This Charm follows the special activation rules of Keen Sight Technique (p. 267).",
                 :prereq-charms "Sensory Acuity Prana",
                 :ability :awareness,
                 :name "Keen Hearing and Touch Technique",
                 :type :simple,
                 :duration "One scene",
                 :page "269",
                 :keywords "None",
                 :min-ability 3,
                 :cost "3m or 6m, 1wp",
                 :character-tags [],
                 :min-essence 1}
                {:description "The Lawgiver’s ears are attuned to the passage of motion. Anything which disturbs the stillness is hers to notice. When a character attempts to move in stealth, the Solar gains +3 dice to spot him.",
                 :prereq-charms "Keen Hearing and Touch Technique",
                 :ability :awareness,
                 :name "Studied Ear Espial",
                 :type :reflexive,
                 :duration "Instant",
                 :page "269",
                 :keywords "None",
                 :min-ability 3,
                 :cost "1m",
                 :character-tags [],
                 :min-essence 1}
                {:description "The Solar’s sense of touch is attuned to movement in the world around her. When a hidden character attempts to move across a surface connected to one the Solar is touching, he accrues an additional -2 penalty to his Stealth roll, in addition to the regular -3 penalty detailed on page 204. This Charm functions within short range of the Solar. She can touch a tree trunk and feel something moving in the lowest branches, sense footsteps approaching her in a pitch black hallway, and other, similar feats. If the target is within range of the Solar’s extended touch upon rolling Join Battle, the Exalt gains three non-Charm dice to her Join Battle roll so long as she cannot see her opponent. If the Exalt has learned Unsurpassed Hearing and Touch Discipline, she can feel such movements out to medium range, and can determine the size, shape, and velocity of her target. She can feel a siaka circling beneath her ship, and she can differentiate between a gecko or an assassin lizard climbing down a wall she’s leaning against.",
                 :prereq-charms "Keen Hearing and Touch",
                 :ability :awareness,
                 :name "Eyeless Harbinger Awareness",
                 :type :reflexive,
                 :duration "One scene",
                 :page "",
                 :keywords "None",
                 :min-ability 3,
                 :cost "3m",
                 :character-tags [],
                 :min-essence 1}
                {:description "At the confluence of mastered senses, the Solar feels second sight growing in her heart. In the moment battle begins, her Awakening Eye reads the flow of Initiative and makes her aware of attacks that will happen in the near future. This Charm supplements a Join Battle roll with a free full (Perception + Awareness) Excellency, and by creating a cascading reroll of 10s. For every 10 rolled, reroll one nonsuccess. Non-successes which reroll 10s provoke more rerolls until a 10 fails to appear in the result. In addition, mark down how many non-successes became successes during the reroll process; every rerolled success adds one to a pool of automatic successes the Solar may use to detect hidden opponents until combat ends. These bonus successes are depleted when the Exalt uses them, though she may choose when and how many successes to use, spreading a number of successes over a number of attempts.",
                 :prereq-charms "Any two Keen (Sense) Techniques",
                 :ability :awareness,
                 :name "Awakening Eye",
                 :type :supplemental,
                 :duration "Instant",
                 :page "270",
                 :keywords "None",
                 :min-ability 4,
                 :cost "5m, 1wp",
                 :character-tags [],
                 :min-essence 1}
                {:description "With flawless gaze and unswerving eye, the Exalt’s vision corrects itself, eating away impurities and anomalies to give her the most perfect view. When contesting a Stealth or Larceny action against the character, this Charm can be used to create a cascading reroll, eliminating non-successes from the Awareness roll as the Solar’s vision corrects itself. After an Awareness roll, record successes and reroll (Essence) non-successes. For each of these dice that turns up a success, reroll another die until the cascade fails to produce any successes. Dice rerolled by Sensory Acuity Prana are not included in the cascade. This Charm may also be used in Join Battle against an opponent the Lawgiver can see.",
                 :prereq-charms "Unswerving Eye Method",
                 :ability :awareness,
                 :name "Inner Eye Focus",
                 :type :reflexive,
                 :duration "Instant",
                 :page "270",
                 :keywords "None",
                 :min-ability 5,
                 :cost "4m",
                 :character-tags [],
                 :min-essence 2}
                {:description "The Lawgiver knows the scent of her kith with the warmth of a lioness, the smell of her enemies with the familiarity of a shark. This Charm adds automatic successes to an Awareness roll to detect hidden characters based on their level of intimacy with the Solar. Minor Intimacies add 1 success, while Major and Defining Intimacies add 2 and 3
                respectively. The Solar need not suspect that one of her
                Ties is hiding nearby; Scent-Honing Prana automatically
                lends itself to applicable rolls without the Solar knowing,
                though the player may always choose to disregard its use.",
                 :prereq-charms "Foe-Scenting Method",
                 :ability :awareness,
                 :name "Scent-Honing Prana",
                 :type :reflexive,
                 :duration "Instant",
                 :page "270",
                 :keywords "None",
                 :min-ability 5,
                 :cost "3m",
                 :character-tags [],
                 :min-essence 2}
                {:description "Even the least sounds fail to escape the Lawgiver’s notice. When attempting to seek out a hidden character with her Awareness, all 1s rolled by her target act as 10s rolled by the Exalt, and all her target’s 2s act as 9s. These 9s are explicitly doubled by Sensory Acuity Prana. Knowing Beyond Silence can be activated after the hiding character’s dice roll. This Charm can be used to enhance a Join Battle roll against a character whom the Exalt is listening for but cannot see.",
                 :prereq-charms "Studied Ear Espial",
                 :ability :awareness,
                 :name "Knowing Beyond Silence",
                 :type :reflexive,
                 :duration "Instant",
                 :page "270",
                 :keywords "None",
                 :min-ability 4,
                 :cost "2m",
                 :character-tags [],
                 :min-essence 2}
                {:description "The Exalt feels the air current around her, and senses even the slightest disruption. In an enclosed space, such as a burial chamber, or a place where high walls or dense foliage stifle gusts of wind, the Exalt can feel the presence of a hidden person displacing the air around her. Add one automatic success to an Awareness roll to detect or Join Battle against such a character.",
                 :prereq-charms "Eyeless Harbinger Awareness",
                 :ability :awareness,
                 :name "Living Pulse Perception",
                 :type :permanent,
                 :duration "Permanent",
                 :page "271",
                 :keywords "None",
                 :min-ability 4,
                 :cost "—",
                 :character-tags [],
                 :min-essence 2}
                {:description "When fighting blind, the Solar’s second sight rises to see through the Essence of the world, momentarily revealing
                her target’s location and allowing her to strike. During combat, the Exalt may use this Charm on her turn to strike at a hidden foe within range. If this attack is successful, it does not knock her opponent out of stealth unless he’s incapacitated by the blow. Instead, it forces him to change hiding places, making him subject to the penalty for moving in Stealth (p. 204). If the target can find a different hiding place without changing range bands, this does not use up his movement action for the turn.",
                 :prereq-charms "Knowing Beyond Silence, Living Pulse Perception",
                 :ability :awareness,
                 :name "Roused Dragon Detection",
                 :type :reflexive,
                 :duration "Instant",
                 :page "271",
                 :keywords "None",
                 :min-ability 5,
                 :cost "1m, 1wp",
                 :character-tags [],
                 :min-essence 2}
                {:description "This Charm permanently upgrades its prerequisite. The Exalt has the eyes of the steeliest raptor. She can spot a field mouse a mile away, read a letter at a hundred yards, and critique the mating habits of insects. In zero visibility environments—such as a silt cloud in the belly of a sunken ship—she sees as if she were in a dense fog, using the rules of Keen Sight Technique. She may pick a face out of a crowd with a casual glance, predict a flash flood by counting distant raindrops, and tell if someone is alive by seeing the blood flow through his skin. Special activation rules: When Keen Sight Technique is active, any sight-based Awareness Charm is reduced in cost by one mote, to a minimum of one. If the character has learned all three Unsurpassed (Sense) Discipline and activates all three Keen (Sense) Techniques, this discount applies to any Awareness Charm.",
                 :prereq-charms "Keen Sight Technique",
                 :ability :awareness,
                 :name "Unsurpassed Sight Discipline",
                 :special-activation-rules "When Keen Sight Technique is",
                 :type :permanent,
                 :duration "Permanent",
                 :page "271",
                 :keywords "None",
                 :min-ability 5,
                 :cost "—",
                 :character-tags [],
                 :min-essence 3}
                {:description "Cast down into the darkness, the Lawgiver has known an absence of sensation greater than the deepest abyss. The wicked cannot hide; their shadows avail them nothing. With but a thought, the Solar can impel her senses toward greater form. The player may reroll any Awareness roll, maintaining the effects of any Charms she paid for on the initial roll and activating any Charms she wishes to pay for to enhance her second attempt.",
                 :prereq-charms "Inner Eye Focus",
                 :ability :awareness,
                 :name "Blink",
                 :type :reflexive,
                 :duration "Instant",
                 :page "271",
                 :keywords "None",
                 :min-ability 5,
                 :cost "1wp",
                 :character-tags [],
                 :min-essence 3}
                {:description "This Charm permanently upgrades its prerequisite. The Solar can track her prey’s scent with the unerring accuracy of a bloodhound, or find her victim’s scent with the methodical sipping of a serpent. The Exalt adds her Perception or a minimum of 2 automatic successes to any Survival-based rolls to track a character or hunt for food or water using her sense of smell, and extends her range for doing so to (half her Essence rounded up) miles. She also gains the ability to scent moods, making an automatically successful scent-based read intentions action to determine a target’s disposition. She can add scentless, tasteless subjects to her scent library and taste index. She can also add items to her taste index by merely smelling them, as well as reference those tastes by smell alone. With a harmless drop on her tongue, she can identify a poison she has tasted, and she can detect a tasteless poison by the way it dilutes a drink or acts as an unknown ingredient in a meal whose flavors are well known to her. In addition, bleeding characters (those with a wound penalty of -1 or greater) and characters who are severely injured (-4 wound penalty) are easier to find. Add 1 or 2 dice to an Awareness roll against the target’s Stealth. This Charm follows the special activation rules of Unsurpassed Sight Discipline (p. 271), discounting the cost of taste and smell effects instead of those which enhance sight.",
                 :prereq-charms "Keen Taste and Smell Technique",
                 :ability :awareness,
                 :name "Unsurpassed Taste and Smell Discipline",
                 :type :permanent,
                 :duration "Permanent",
                 :page "",
                 :keywords "None",
                 :min-ability 5,
                 :cost "—",
                 :character-tags [],
                 :min-essence 3}
                {:description "This Charm permanently upgrades its prerequisite. The Lawgiver can listen in on a whispered conversation a mile away in still air, or in noisy conditions, such as a raging battlefield, out to long range. She can hear a thunderstorm burgeoning, an army decamping, a tyrant lizard roaring, and other loud noises at (Essence * 5) miles. She can read by passing her fingers over a page and feeling the ink beneath her fingertips. This Charm also confers the following techniques to the Solar: Conjure Image: For one mote, the Exalt can visualize an object she is touching, in sections no larger than a horse’s head. She can identify a familiar face in a pitch black crypt, but might need several activations to visualize the fossil skeleton of an ancient behemoth in a lightless cavern. Sense Current: For one mote, the Exalt can feel the lightest motion of air, orienting herself to the exit in even the most lightless of conditions. Read the Web: For five motes committed, the Exalt can listen in on a conversation behind a thick door, just by touching a connecting wall or surface. She feels the vibrations in her fingertips, and her senses translate them to words she can hear. This is a scene length effect, and its range can be extended up to (Essence x100) yards by running a wire from the Exalt’s fingertips into a chamber where her targets are speaking. Sound from Stillness Meditation: For six motes, one Willpower, the Solar can take a Simple action lasting five minutes to filter Creation, listening for specific sounds or conversations that have already happened. The Exalt draws audio from the vibrations of sounds stored in her surroundings—usually rocks and trees—and may listen for noises or conversations that happened up to (Essence x5) hours prior to her arrival with a difficulty 5 Awareness roll. For the duration of the technique, the Solar must remain still, listening intently as she filters out the garbled static and unwanted sounds to reach the reverberations she’s searching for. As this technique only lasts five minutes, the Solar can only glean up to half that amount in useful audio. Unsurpassed Hearing and Touch follows the special activation rules of Unsurpassed Sight Discipline (p. 271), discounting the cost of hearing and touch effects instead of those which enhance sight. This Charm can never discount the cost of its own techniques.",
                 :sound-from-stillness-meditation "For six motes, one",
                 :prereq-charms "Keen Hearing and Touch Technique",
                 :ability :awareness,
                 :name "Unsurpassed Hearing and Touch Discipline",
                 :type :reflexive,
                 :duration "Permanent",
                 :page "",
                 :keywords "None",
                 :sense-current "For one mote, the Exalt can feel the lightest",
                 :min-ability 5,
                 :conjure-image "For one mote, the Exalt can visualize",
                 :cost "—",
                 :character-tags [],
                 :min-essence 3,
                 :read-the-web "For five motes committed, the Exalt can"}
                {:description "The Lawgivers can listen across vast spaces for the sound of a favored voice. The Exalt must have activated Keen Hearing and Touch Technique in order to use this Charm. Upon doing so, the Exalt becomes aware any time she is addressed by someone for whom she holds a Major or Defining positive Intimacy, no matter how far away he is. So long as she’s on the same plane of existence as they are, the Solar can hear the words of her favored people clearly, as if they were in the same room, so long as they are addressing their speech to her. This Charm’s duration is Indefinite: each time a character addresses the Solar, she has an instant in which she feels a tingle in the base of her skull, telling her to tune her hearing and listen. Upon activating the Charm, she can hear everything her compatriot wishes to say to her, until the character has been silent for ten seconds or longer. The cost of this Charm cannot be reduced by its prerequisite. ",
                 :prereq-charms "Unsurpassed Hearing and Touch Discipline",
                 :ability :awareness,
                 :name "Dedicated Unerring Ear",
                 :type :reflexive,
                 :duration "Indefinite",
                 :page "273",
                 :keywords "None",
                 :min-ability 5,
                 :cost "3m per exchange",
                 :character-tags [],
                 :min-essence 4}
                {:description "Solars are the legacy of the Unconquered Sun. It is their destiny to see the world through this age of darkness. When this Charm is used, the Solar’s Caste Mark blazes like a tiny sun, cancelling any Essence-muting magic the Solar may be using, and removing her from stealth. Eyes blazing white, Caste Mark burning, her gaze shines a wide beam of light across everything she searches, twin lamps moving over the terrain out to long range. Everything caught in her stare is subject to the following effects:
                • All magical and mundane Stealth effects are cancelled. Solid walls and other opaque objects grow transparent as the Lawgiver’s gaze passes over them, rendering all forms of Stealth automatically unsuccessful.
                • Fog lifts, smoke parts, and clouds dissolve under the Solar’s intense focus.
                • Dematerialized spirits are forced to materialize, at full cost of the Materialize Charm, or as much of the cost as they can pay.
                • All disguise magic is stripped. Mundane disguises tatter and melt away.
                • Shapeshifters are forced back into natural form, resplendent destinies are temporarily forced into dormancy, personas (p. 400) are suppressed, and other innate or native transformative magics of the Exalted are similarly deactivated. The only way to avoid Eye of the Unconquered Sun is to successfully dodge the Solar’s gaze by applying Evasion against the Solar’s Awareness roll. The Solar’s Awareness roll is enhanced by (Essence) dice, and any 1s rolled are rerolled until 1s fail to appear. Every character within long range of the Solar who fails to dodge when she uses Eye of the Unconquered Sun is subject to the above effects. The range of this Charm is extended to extreme range by Unsurpassed Sight Discipline, however, this Charm does not depend on eyesight and may be learned and employed by a blind Exalt. Anyone spotted by Eye of the Unconquered Sun automatically knows it; a bright white glare piercing through a fortress wall or an airship hull is impossible to miss.",
                 :prereq-charms "Awakening Eye + Any 3 non-Excellency Awareness Charms",
                 :ability :awareness,
                 :name "Eye of the Unconquered Sun",
                 :type :simple,
                 :duration "One turn",
                 :page "273",
                 :keywords "None",
                 :min-ability 5,
                 :cost "10m, 1wp",
                 :character-tags [],
                 :min-essence 4}])